name: 优化提议
description: 新功能提议，对已有功能进行增强
title: '[Feat]: '
labels: [ "enhancement" ]

body:
  - type: markdown
    attributes:
      value: |
        ## 感谢你的提议
        ## 以下是一些注意事项，请务必阅读让我们能够更容易处理

        ### ❗ | 确定没有相同问题的 Feature 已被提出或实现。
        ### 📝 | 确定现有的PR和代码并没有该功能的实现/相似的功能。 
        ### 如果您不知道如何有效、精准地表述，我们建议先阅读 [《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md#%E4%BD%BF%E7%94%A8%E6%9C%89%E6%84%8F%E4%B9%89%E4%B8%94%E6%8F%8F%E8%BF%B0%E6%98%8E%E7%A1%AE%E7%9A%84%E6%A0%87%E9%A2%98)

        ---
  - type: checkboxes
    id: terms
    attributes:
      label: 请确保您已阅读以上注意事项，并勾选下方的确认框。
      options:
        - label: "我确定这是一个从未被提出和实现过的功能。"
          required: true
        - label: "我已经在 [Issue Tracker](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools/issues) 以及 [Pull Request](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。"
          required: true
        - label: 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 并不是关于本插件的提议，则我的 Issue 可能会被无条件自动关闭或/并锁定。
          required: true
        - label: 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。
          required: true

  - type: textarea
    id: feature-to-add
    attributes:
      label: 需要添加的功能内容
      description: |
        请具体提出想添加的功能，包括实现的模拟（如有）
        是否有类似的功能已经实现？如有请肯定地提出与该功能不同的地方/想改进/添加该功能的哪一部分。
    validations:
      required: true